### PR TITLE
Add .Net 8.0 Support

### PR DESCRIPTION
**Pull request by fastman61**

### CODE REVIEW

**Comment by Eastrall** [comment]
Build is failing. Can you also update `.github/workflows/build.yml` to add .NET 8 support ?
https://github.com/Eastrall/EntityFrameworkCore.DataEncryption/blob/ea6836b7b82f5548f9ccc2bc67c3c8aada662b2c/.github/workflows/build.yml#L17-L24

**Comment by periapsistech** [comment]
Let me know if I can help. Need this upgrade as well.

**Review by sezer — APPROVED** [review]

**Comment by fastman61** [comment]
I push my commits to fix the build error. Can you check it?

**Comment by periapsistech** [comment]
Any update on this?

**Review by Eastrall — APPROVED** [review]

**Comment by Eastrall** [comment]
CI is passing, looks good to me. Merging. Thanks for the contribution!

**Pull request merged**
