### PR TITLE
Version 4.0.0

### PR DESCRIPTION
**Pull request by Eastrall**
# Version 4.0.0

## Added

- Add .NET 7 support (#42)
- Add fluent annotation support (#44)
- Add fluent API sample

### ⚠️ **BREAKING CHANGE** ⚠️
- Changed `IEncryptionProvider` interface to be simpler to use:
  - `byte[] Encrypt(byte[] input)` instead of ` TStore Encrypt<TStore, TModel>(TModel dataToEncrypt, Func<TModel, byte[]> converter, Func<Stream, TStore> encoder);`
  - `byte[] Decrypt(byte[] input)` instead of `TModel Decrypt<TStore, TModel>(TStore dataToDecrypt, Func<TStore, byte[]> decoder, Func<Stream, TModel> converter);`

### Other changes

- Add GitHub action support with build matrix (.NET Core 3.1, .NET 5, .NET 6, .NET 7)
- Update `README.md` documentation for creating a custom encryption provider. (#37)
- Update projects to C# 10 and file scoped namespaces

### ⚠️ **BREAKING CHANGE** ⚠️ 

- Removing constructor `AesProvider(byte[] key, CipherMode mode = CipherMode.CBC, PaddingMode padding = PaddingMode.PKCS7)` on `AesProvider`.
  - To use a dynamic IV, use the following constructor: `public AesProvider(byte[] key, byte[] initializationVector, CipherMode mode = CipherMode.CBC, PaddingMode padding = PaddingMode.PKCS7)` and set `initializationVector` to `null`.
- Removed Data Migration support.

### Other removals

- Remove AzureDevOps pipelines.

### CODE REVIEW

**Review by sominola — COMMENTED** [review]
)

**Review by Uli-Armbruster — APPROVED** [review]

**Review by Uli-Armbruster — APPROVED** [review]
looks good to me

**Review by DerStimmler — APPROVED** [review]

**Comment by Eastrall** [comment]
@Uli-Armbruster I need to run some more tests for byte[] encryption as a `Base64` string, I noticed that V3.X has a major issue with this scenario. Encryption process goes well, but decryption process adds some extra 0 bytes to the original value, and unfortunatly there nothing I can do about it. So, I will most likely drop the support for encrypting a byte[] as a Base64 string.

I'll keep you updated on this.

**Comment by Uli-Armbruster** [comment]
> @Uli-Armbruster I need to run some more tests for byte[] encryption as a `Base64` string, I noticed that V3.X has a major issue with this scenario. Encryption process goes well, but decryption process adds some extra 0 bytes to the original value, and unfortunatly there nothing I can do about it. So, I will most likely drop the support for encrypting a byte[] as a Base64 string.
> 
> I'll keep you updated on this.

For my understanding: When I have an Entity with a property of type byte[], then there would be under certain circumstances failures in encryption since extra 0 bytes are added?

**Pull request merged**
